apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: mynamespace
  labels:
    app.kubernetes.io/name: nginx-pod
    app.kubernetes.io/instance: nginx-pod-123456
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: application
    app.kubernetes.io/managed-by: manually
  annotations:
    imageregistry: "https://hub.docker.com/"

spec:
  containers:
    - name: mynginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
